Repository UriahShaulMandel/BaldPhone, pull requests merged in 2019-11, with the labels that each got.

#96 Update strings.xml
  app/src/main/res/values-sl/strings.xml
Labels: merge when green

#117 [locale] add Russian language
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/ntstrings.xml
  translating/TRANSLATING.md
Labels: translation

#121 correct typo in string
  app/src/main/res/values/strings.xml
Labels: typo-fix

#134 Some settings UI fixes, #131 #102
  app/src/main/java/com/bald/uriah/baldphone/activities/SettingsActivity.java
  app/src/main/java/com/bald/uriah/baldphone/views/BaldTitleBar.java
Labels: UI, enhancement

#147 Apps activity changes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bald/uriah/baldphone/activities/AppsActivity.java
Labels: merge when green

#148 Fixed #130 - Contact menu: When a contact is open, the rows are too f…
  app/src/main/res/layout/contact_add_to.xml
  app/src/main/res/layout/contact_address.xml
  app/src/main/res/layout/contact_mail.xml
  app/src/main/res/layout/contact_number.xml
Labels: UI, enhancement, merge when green
